$(function() {
    $("#dianji1").click(
        function(){
            $("#dianji1").next().toggle();
        }
    );
    $("#dianji2").click(
        function(){
            $("#dianji2").next().toggle();
        }
    );
    $("#dianji3").click(
        function(){
            $("#dianji3").next().toggle();
        }
    )
    $("#dianji4").click(
        function(){
            $("#dianji4").next().toggle();
        }
    )
    $("#dianji8").click(
        function(){
            $("#dianji8").next().toggle();
        }
    )
    $("#dianji9").click(
        function(){
            $("#dianji9").next().toggle();
        }
    )
    $("#dianji5").click(
        function(){
            $("#dianji5").next().toggle();
        }
    )
    $("#dianji6").click(
        function(){
            $("#dianji6").next().toggle();
        }
    )
    $("#dianji7").click(
        function(){
            $("#dianji7").next().toggle();
        }
    )
});